Repository openshift/oauth-proxy, pull requests merged in 2018-11, with the labels that each got.

#93 Add a base Dockerfile and Makefile
  Dockerfile
  Makefile
Labels: size/S

#89 Fix cert auth options
  http.go
  main.go
  options.go
  providers/openshift/authentication.go
  providers/openshift/provider.go
Labels: lgtm, size/S

#84 Visual updates to help set apart when the 2 login forms are displayed together ...
  templates.go
Labels: size/M
