Repository openshift/oauth-proxy, pull requests merged in 2019-02, with the labels that each got.

#96 fixing http/s proxy handling for openshift provider
  providers/openshift/provider.go
Labels: approved, lgtm, ok-to-test, size/XS

#100 fix review/user validation URLs
  providers/openshift/provider.go
Labels: approved, lgtm, size/M

#101 openshift provider: refetch oauth endpoints on login
  oauthproxy.go
  options.go
  providers/openshift/provider.go
  providers/provider_data.go
  providers/provider_default.go
  providers/providers.go
Labels: approved, lgtm, size/L

#102 providers: don't cache login and redeem URLs
  oauthproxy.go
  oauthproxy_test.go
  options.go
  providers/openshift/provider.go
  providers/provider_data.go
  providers/provider_default.go
  providers/providers.go
Labels: approved, lgtm, size/L

#103 Bug 1678645: fix(Dockerfile): build and label from Dockerfile
  Dockerfile
  Dockerfile.rhel7
  images/Dockerfile
Labels: approved, lgtm, size/M
