Repository openshift/oauth-proxy, pull requests merged in 2020-03, with the labels that each got.

#158 Document "cookie-secret-file" CLI argument
  README.md
Labels: approved, lgtm, size/XS

#160 [release-4.3] Bug 1809253: Reload serving certs
  Gopkg.lock
  dynamiccertificates/cert_key.go
  dynamiccertificates/client_ca.go
  dynamiccertificates/doc.go
  dynamiccertificates/dynamic_cafile_content.go
  dynamiccertificates/dynamic_serving_content.go
  dynamiccertificates/named_certificates.go
  dynamiccertificates/tlsconfig.go
  dynamiccertificates/util.go
  dynamiccertificates/wait.go
  http.go
  vendor/github.com/golang/groupcache/.gitignore
  vendor/github.com/golang/groupcache/.travis.yml
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/README.md
  vendor/github.com/golang/groupcache/byteview.go
  vendor/github.com/golang/groupcache/byteview_test.go
  vendor/github.com/golang/groupcache/consistenthash/consistenthash.go
  vendor/github.com/golang/groupcache/consistenthash/consistenthash_test.go
  vendor/github.com/golang/groupcache/groupcache.go
  vendor/github.com/golang/groupcache/groupcache_test.go
  vendor/github.com/golang/groupcache/groupcachepb/groupcache.pb.go
  vendor/github.com/golang/groupcache/groupcachepb/groupcache.proto
  vendor/github.com/golang/groupcache/http.go
  vendor/github.com/golang/groupcache/http_test.go
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/github.com/golang/groupcache/lru/lru_test.go
  vendor/github.com/golang/groupcache/peers.go
  vendor/github.com/golang/groupcache/singleflight/singleflight.go
  vendor/github.com/golang/groupcache/singleflight/singleflight_test.go
  vendor/github.com/golang/groupcache/sinks.go
  vendor/github.com/golang/groupcache/testpb/test.pb.go
  vendor/github.com/golang/groupcache/testpb/test.proto
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/XXL

#164 [release-4.2] Bug 1809258: Reload serving certs
  Gopkg.lock
  dynamiccertificates/cert_key.go
  dynamiccertificates/client_ca.go
  dynamiccertificates/doc.go
  dynamiccertificates/dynamic_cafile_content.go
  dynamiccertificates/dynamic_serving_content.go
  dynamiccertificates/named_certificates.go
  dynamiccertificates/tlsconfig.go
  dynamiccertificates/util.go
  dynamiccertificates/wait.go
  http.go
  vendor/github.com/golang/groupcache/.gitignore
  vendor/github.com/golang/groupcache/.travis.yml
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/README.md
  vendor/github.com/golang/groupcache/byteview.go
  vendor/github.com/golang/groupcache/byteview_test.go
  vendor/github.com/golang/groupcache/consistenthash/consistenthash.go
  vendor/github.com/golang/groupcache/consistenthash/consistenthash_test.go
  vendor/github.com/golang/groupcache/groupcache.go
  vendor/github.com/golang/groupcache/groupcache_test.go
  vendor/github.com/golang/groupcache/groupcachepb/groupcache.pb.go
  vendor/github.com/golang/groupcache/groupcachepb/groupcache.proto
  vendor/github.com/golang/groupcache/http.go
  vendor/github.com/golang/groupcache/http_test.go
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/github.com/golang/groupcache/lru/lru_test.go
  vendor/github.com/golang/groupcache/peers.go
  vendor/github.com/golang/groupcache/singleflight/singleflight.go
  vendor/github.com/golang/groupcache/singleflight/singleflight_test.go
  vendor/github.com/golang/groupcache/sinks.go
  vendor/github.com/golang/groupcache/testpb/test.pb.go
  vendor/github.com/golang/groupcache/testpb/test.proto
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm
