Repository openshift/oauth-proxy, pull requests merged in 2023-07, with the labels that each got.

#258 APPSRE-7970: Add support for configuring upstream timeout
  README.md
  main.go
  oauthproxy.go
  oauthproxy_test.go
  options.go
Labels: lgtm, approved, jira/valid-reference

#257 fix route apiVersion
  contrib/sidecar.yaml
Labels: lgtm, approved, ok-to-test

#261 [4.13] OCPBUGS-16805: Updating golang-github-openshift-oauth-proxy images to be consistent with ART
  .ci-operator.yaml
  Dockerfile
  oauthproxy_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
