Repository openshift/oauth-proxy, pull requests merged in 2024-12, with the labels that each got.

#289 OCPBUGS-44319: Fix oauth-proxy e2e-component tests
  test/e2e/proxy_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#285 OCPBUGS-42251: Fix oauth-proxy e2e-component tests
  test/e2e/proxy_test.go
Labels: jira/valid-bug, jira/valid-reference

#301 [release-4.18] OCPBUGS-45820: Fix oauth-proxy e2e-component tests
  test/e2e/proxy_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
